### ISSUE TITLE
Path for pytorch 2.4 release

### ISSUE THREAD

**Issue by das-intensity** [conda-forge/pytorch3d-feedstock#15]
### Comment:

I've got users who want pytorch3d on conda to have support for pytorch 2.4, so I'd like to understand the "process" of how this comes about.

Here's my undersatnding, please let me know if this sound correct:
1. A new version must first be pushed to [pytorch-cpu-feedstock](https://github.com/conda-forge/pytorch-cpu-feedstock), and it seems this is WIP in https://github.com/conda-forge/pytorch-cpu-feedstock/pull/248
2. Next a PR in the [conda-forge-pinning-feedstock](https://github.com/conda-forge/conda-forge-pinning-feedstock) repo must adopt this new version, e.g. for 2.3: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5895
3. The @regro-cf-autotick-bot should then automatically put up a PR for an updated pytorch version for pytorch3d e.g. for 2.3: https://github.com/conda-forge/pytorch3d-feedstock/pull/12
4. Once accepted, a new release (same pytorch3d version as already released) will be built and uploaded to conda repos

That all sound about right?

**Comment by Tobias-Fischer** [comment]
Yes that’s correct
